#!/bin/zsh

# global variables
cwd="$(pwd)"
server="/Users/jonas-mika/programming/webdev/jonas-mika.de/heroku-server/assets"

# query source file

cwd=($(ls -l -p | grep -v / | tr -s ' ' ' ' | cut -d ' ' -f9 | grep '\S'))
i=1
for file in ${cwd[@]}
do 
  echo "[$i] $file"
  i=$((i+1))
done

echo "\nWhich file(s) do you want to publish?"
read ans"?>>> Choose numbers (whitespace-separated) [1-$((i-1))]: "
files=(${(s/ /)ans})

for i in ${files[@]}
do
  source=${cwd[i]}

  ps=($(ls -R -p ~/programming/webdev/jonas-mika.de/server/assets | grep /  | grep "^/" | cut -d/ -f9- | tr ':' ' '))

  i=1
  for p in ${ps[@]}
  do 
    echo "[$i] $p"
    i=$((i+1))
  done
  echo "\nWhere should $source be located?"

  read num2"?Choose Path [1-$((i-1))]: "
  dest=${ps[$num2]}
  echo "" 

  while true; do
    read yn"?>>> Move file ./$source to $dest? [y/n]"
    case $yn in
        [Yy]* ) 
          /bin/cp "$source" "$server/$dest";
          echo "Moved file succesfully\n";
          break;;
        [Nn]* ) 
          echo "Didn't move\n"; break;;
        * ) 
          echo "Please answer [y]es or [n]o\n";;
    esac
  done;
done;

while true; 
do
  read yn"?Do you want to publish the changes? [y/n]"
  case $yn in 
      [Yy]* ) 
        cd $server; cd ..;
        git add -A
        git commit -am "changes to static files"
        git push heroku master
        cd $cwd
        break;;
      [Nn]* ) echo "Didn't push changes"; break;;
      * ) echo "Please answer yes or no.";;
  esac
done;
